Rename fbt to mf
the-lifted-initiative/many-framework pull request #79
Opened 2022-05-09 04:29 UTC by hansl

This is based on #78. The only change is renaming any instances of `FBT` to `MF`.

2022-05-12 18:47 UTC, stanleyjones approved these changes

2022-05-12 19:16 UTC, fmorency requested changes
You need to change the hash in both `ledger_state.json` files.

```
May 12 15:17:17.465 DEBUG many_ledger: Opts { verbose: 2, quiet: 0, pem: "/home/fmorency/Identities/id1.pem", addr: 127.0.0.1:8000, abci: false, state: Some("staging/ledger_state.json"), persistent: "ledger.db", clean: true }
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ManyError { code: AttributeSpecific(-20005), message: Some("Invalid initial state hash. Expected '{expected}', was '{actual}'."), arguments: {"actual": "5b28eb27f0977f8c5a9d4f6eb6c0ac15c1af6fde04d80297c7eba54f9178d5df", "expected": "cb619c8805b749b23486bbe3dfdb8134d9df5251763cfb48d48ecd763cea215e"} }', src/many-ledger/src/main.rs:103:70
```

2022-05-13 15:16 UTC, hansl commented
@fmorency done.

2022-05-13 15:52 UTC, fmorency approved these changes

2022-05-13 20:01 UTC, merged